### ISSUE TITLE
would you like to provide this json file ('../../json/sklearn_randomforest_keck_pria_only.json') for your test.ipynb 

### ISSUE THREAD

**Issue by xuzhang5788** [gitter-lab/pria_lifechem#28] opened 2019-05-30 01:07 UTC
I tried to run your test.ipynb. But I couldn't find '../../json/sklearn_randomforest_keck_pria_only.json' this file in you github. Would you like to provide it? Thanks

**Comment by chao1224** [comment] 2019-05-30 16:38
Hi @xuzhang5788, can you try replace `../../json/sklearn_randomforest_keck_pria_only.json` with `../../json/sklearn_randomforest.json`? Does that work for you?

**Comment by xuzhang5788** [comment] 2019-05-30 18:08
@chao1224 
Sorry, No. 
When I run cell 3, I got 

process id: 0
Testing set: {'class_weight': 'balanced', 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 4000}

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-f62c3d7d1a6f> in <module>()
----> 1 task = SKLearn_RandomForest(conf=conf)

<ipython-input-1-e0a4decd4260> in __init__(self, conf)
     61 
     62         self.model_dict = {}
---> 63         self.useVal = bool(conf['useVal'])
     64         return
     65 

KeyError: 'useVal'

**Comment by chao1224** [comment] 2019-05-30 18:59
@xuzhang5788  I see. Can you try one more thing?
Replace `self.useVal = bool(conf['useVal'])` with `self.useVal = False`.

Sry this is using an old env, and I don't have it on my server right now. I can recreate it if things don't work out.

**Comment by xuzhang5788** [comment] 2019-05-30 19:56
@chao1224 
Sorry. It still doesn't work.

process id: 0
Testing set: {'class_weight': 'balanced', 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 4000}

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f62c3d7d1a6f> in <module>()
----> 1 task = SKLearn_RandomForest(conf=conf)

<ipython-input-4-c082cfb6e028> in __init__(self, conf)
     62         self.model_dict = {}
     63         #self.useVal = bool(conf['useVal'])
---> 64         self.useVal = False
     65         return
     66 

AttributeError: can't set attribute

**Comment by chao1224** [comment] 2019-05-30 21:51
@xuzhang5788 I'm not sure if you are using the same conda env.

I tried to reinstall everything (codes, dataset, and conda env). The notebook has been updated.

**Comment by xuzhang5788** [comment] 2019-05-31 00:43
@chao1224 
Thank you for your response. I retried it, but I still had the same error message. My python is python3. I have changed your .py files into python3 files.

**Comment by chao1224** [comment] 2019-05-31 01:45
@xuzhang5788 Then I think it should be the anaconda environment(like python version) issue. To make sure the results are reproducible, I personally would recommend you try the same environment.

**Comment by agitter** [comment] 2019-05-31 11:16
@xuzhang5788 I was thinking the same thing as @chao1224.  Are you running inside the exact same conda environment that we describe [here](https://github.com/gitter-lab/pria_lifechem#installation)?  It is not enough to use Python 3.  We have seen that the APIs for some of the major packages can change so it is necessary to lock the version of those packages in order to rerun our code.

**Comment by agitter** [comment] 2019-06-22 20:36
@xuzhang5788 were you able to get this working inside the conda environment?  Please let us know if you need additional help or if we should close this issue.

**Comment by xuzhang5788** [comment] 2019-06-24 19:33
@agitter 
Thank you so much for your reply. Today I followed your instruction and set conda environment using  
conda env create -f conda_env.yml python=2.7 
and also changed my jupyter notebook setting with python2. When I run test.ipynb, I still got error messages like this:
in the first cell:
LookupError                               Traceback (most recent call last)
<ipython-input-1-a6abc3e97a23> in <module>()
      7 sys.path.insert(0, '..')  # Add path from parent folder
      8 sys.path.insert(0, '.')  # Add path from current folder
----> 9 from evaluation import *
     10 from function import *
     11 from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

/media/pharma1/projects/pria_lifechem/pria_lifechem/evaluation.py in <module>()
      4 import numpy as np
      5 from sklearn.metrics import roc_auc_score, average_precision_score, precision_recall_curve, roc_curve
----> 6 import rpy2.robjects as robjects
      7 import rpy2.robjects.packages as rpackages
      8 from sklearn.metrics import auc

/home/pharma1/anaconda3/envs/pria/lib/python2.7/site-packages/rpy2/robjects/__init__.py in <module>()
     17 import rpy2.rlike.container as rlc
     18 
---> 19 from rpy2.robjects.robject import RObjectMixin, RObject
     20 from rpy2.robjects.vectors import (BoolVector,
     21                                    IntVector,

/home/pharma1/anaconda3/envs/pria/lib/python2.7/site-packages/rpy2/robjects/robject.py in <module>()
     56     return rpy2type(rinterface_level)
     57 
---> 58 class RObjectMixin(object):
     59     """ Class to provide methods common to all RObject instances """
     60     __rname__ = None

/home/pharma1/anaconda3/envs/pria/lib/python2.7/site-packages/rpy2/robjects/robject.py in RObjectMixin()
     69     __rclass = rpy2.rinterface.baseenv.get("class")
     70     __rclass_set = rpy2.rinterface.baseenv.get("class<-")
---> 71     __show = rpy2.rinterface.baseenv.get("show")
     72 
     73     __slots = None

LookupError: 'show' not found

but when I use jupyter notebook with python3,
first two cells are working well, but the cell three showed 
process id: 0
Testing set: {'class_weight': 'balanced', 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 4000}

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f62c3d7d1a6f> in <module>()
----> 1 task = SKLearn_RandomForest(conf=conf)

<ipython-input-1-a6abc3e97a23> in __init__(self, conf)
     61 
     62         self.model_dict = {}
---> 63         self.useVal = False
     64         return
     65 

AttributeError: can't set attribute

I don't know why.

**Comment by Malnammi** [comment] 2019-06-24 20:09
@xuzhang5788 sorry for the late reply. I believe the issue is being caused by this part of the code:
```
    @property    
    def useVal(self):
        return self.useVal
```
Can you please try removing this and running it again in the python 3 environment?

**Comment by xuzhang5788** [comment] 2019-06-24 20:53
@Malnammi 
Thank you for your solution. It works. 
I found there is a typo in def run on line 24
print (rain_index, val_index, test_index) should be print (train_index, val_index, test_index)
on line 18
it is better to use "test_index = int(running_index / 4)" to keep test_index as an integer. python3 will get a float if use  "test_index = running_index / 4"  
Thank you again

**Closed as completed** 2019-06-24 20:53 UTC

**Comment by agitter** [comment] 2019-06-24 22:05
Thanks for finding this @Malnammi and the typo correction @xuzhang5788 

@Malnammi should we make a pull request to fix this typo in the notebook?
